config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resources :games do
    put :start, on: :member
    resources :rounds, only: :create
    resources :votes, only: :create
    resources :players, only: :create do
      get "/join", to: "players#create", on: :collection
    end
  end

  resources :rounds do
    resources :associations
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :players, dependent: :destroy
  has_many :rounds, dependent: :destroy
  belongs_to :image_pack, optional: true # TODO: remove optional

  serialize :host_ids_order, coder: JSON

  enum status: {
    created: 0,
    in_progress: 1,
    finished: 2
  }

  delegate :status, to: :current_round, prefix: true
  delegate :players_with_associations, to: :current_round, prefix: false
  delegate :players_with_votes, to: :current_round, prefix: false

  def next_host
    player_id = host_ids_order[(rounds.count) % host_ids_order.count]
    players.find(player_id)
  end

  def current_host
    return default_host if created?

    current_round.host
  end

  def default_host
    @default_host ||= players.find_by(user: self.user)
  end

  def shuffled_players
    @shuffled_players ||= players.shuffle
  end

  def distribute_images!
    available_images = image_pack.images
    images_count_per_player = available_images.count / players.count
    game_images = available_images.sample(images_count_per_player * players.count)
    game_images.each_slice(images_count_per_player).with_index do |images, index|
      shuffled_players[index].images << images
    end
  end

  def valid_user?(user)
    players.pluck(:user_id).include?(user.id)
  end

  def valid_player?(player)
    player_ids.include?(player.id)
  end

  def player_role(player)
    return unless valid_player?(player)

    current_host == player ? :host : :player
  end

  def current_round
    rounds.last
  end

  def player_by_user(user)
    players.find_by(user:)
  end

  def create_next_round!
    return if rounds.unfinished.any?

    rounds.create(host: next_host)
  end

  def sync_status!
    finished! if rounds.count == players.count
  end

  def players_without_host
    players.excluding(current_host)
  end
end

app/controllers/games_controller.rb
class GamesController < BaseController
  before_action :validate_current_user!, only: :show
  helper_method :current_player

  def index
    # TODO: show not only hosted games
    @games = current_user.games.all
  end

  def create
    current_player = current_user.players.create
    game = current_user.games.create(players: [current_player], image_pack: ImagePack.first)
    redirect_to game_path(game)
  end

  def show
    current_player
  end

  def start
    ActiveRecord::Base.transaction do
      game.update!(host_ids_order: game.players.ids.shuffle)
      game.in_progress!
      game.create_next_round!
      game.distribute_images!
    end

    update_game_view(game)
  end

  private

  def validate_current_user!
    return if game.valid_user?(current_user)

    flash[:alert] = "You do not have access to this game!"
    redirect_to request.referer || root_path
  end

  def current_player
    @current_player ||= game.player_by_user(current_user)
  end

  def game
    @game ||= Game.find(params[:id])
  end
end

app/views/games/host/_created.html.erb
<%# locals: (game:) %>

Wait other players and start game

<%= render "shared/players/list", players: game.players %>

<div data-controller="clipboard" data-clipboard-success-content-value="Copied!">
  <input type="text" value="<%= join_game_players_url(game.id) %>" data-clipboard-target="source" />

  <button type="button" data-action="clipboard#copy" data-clipboard-target="button">Copy to clipboard</button>
</div>

<div>
  <%= qr_code_svg(join_game_players_url(game.id)) %>
</div>

<%= button_to "Start", start_game_path, method: :put %>

app/views/games/host/_finished.html.erb
<%# locals: (game:, current_player:) %>

table with round results

<%= render "shared/finished/table", players: game.players %>

<%= button_to "Next round", game_rounds_path(game), method: :post %>

app/views/games/host/_guessing.html.erb
wait wile players try to guess your card

<%= render "shared/players/with_votes", players: game.players_without_host %>

app/views/games/host/_host_choice.html.erb
<%# locals: (game:, current_player:) %>

Choose image and create association
<%= render "associations/form", game:, images: current_player.images_on_hand, host: true %>

app/views/games/host/_players_choice.html.erb
Wait all players select images
table with players

<%= render "shared/players/with_association", players: game.players_without_host %>